I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 210, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 210, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
OSError: Couldn't find file 'gui/window_icon.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 210, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "renpy/common/00start.rpy", line 210, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\display\core.py", line 3341, in interact
    self.start()
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\display\core.py", line 2249, in start
    self.post_init()
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\display\core.py", line 2330, in post_init
    self.set_icon()
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\display\core.py", line 2369, in set_icon
    with renpy.loader.load(icon) as f:
  File "C:\Users\fanch\OneDrive\Bureau\Ren'py\renpy-8.0.3-sdk\renpy\loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'gui/window_icon.png'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Carnival Unending 1.0
Sun Apr 30 18:19:58 2023
